# netlify.toml
[build]
  publish   = "public"        # ビルド出力 (静的ファイル) のディレクトリ
  functions = "functions"   # Functions コードを置くディレクトリ

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

[build.environment]
  NODE_VERSION = "18"
